/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Janis Zeps (https://sketchfab.com/zeps9001)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/wall-eanimated-a6758de2e5a04f9e821596592ef4279c
title: Wall-E(Animated)
*/

import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() =>{
    actions.Scene.play();
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group  rotation={[2.2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.trackGears1_low_wall_e_0.geometry}
              material={nodes.trackGears1_low_wall_e_0.material}
            />
          </group>
          <group  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.eyes_low_wall_e_0.geometry} material={nodes.eyes_low_wall_e_0.material} />
          </group>
          <group  rotation={[-1.73, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.neck_low_wall_e_0.geometry} material={nodes.neck_low_wall_e_0.material} />
          </group>
          <group  rotation={[-2.18, 0, 0]} scale={100}>
            <mesh geometry={nodes.hand_low_wall_e_0.geometry} material={nodes.hand_low_wall_e_0.material} />
          </group>
          <group  rotation={[2.2, 0, 0]} scale={[100, 89.33, 89.33]}>
            <mesh
              geometry={nodes.trackGears2_low_wall_e_0.geometry}
              material={nodes.trackGears2_low_wall_e_0.material}
            />
          </group>
          <group  rotation={[2.2, 0, 0]} scale={[100, 69.85, 69.85]}>
            <mesh
              geometry={nodes.trackGears4_low_wall_e_0.geometry}
              material={nodes.trackGears4_low_wall_e_0.material}
            />
          </group>
          <group  rotation={[2.2, 0, 0]} scale={[100, 54.08, 54.08]}>
            <mesh
              geometry={nodes.trackGears3_low_wall_e_0.geometry}
              material={nodes.trackGears3_low_wall_e_0.material}
            />
          </group>
          <group  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.eyes_low001_eyes_0.geometry} material={materials.eyes} />
          </group>
          <group  rotation={[-1.45, 0, 0]} scale={100}>
            <mesh geometry={nodes.hand_low001_wall_e_0.geometry} material={nodes.hand_low001_wall_e_0.material} />
          </group>
          <group  rotation={[-1.62, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.hand_low002_wall_e_0.geometry} material={nodes.hand_low002_wall_e_0.material} />
          </group>
          <group  rotation={[2.51, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low_wall_e_0.geometry} material={nodes.track_low_wall_e_0.material} />
          </group>
          <group  rotation={[2.38, -0.01, 0]} scale={100}>
            <mesh geometry={nodes.track_low001_wall_e_0.geometry} material={nodes.track_low001_wall_e_0.material} />
          </group>
          <group   scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low002_wall_e_0.geometry} material={nodes.track_low002_wall_e_0.material} />
          </group>
          <group rotation={[2.24, -0.01, 0]} scale={100}>
            <mesh geometry={nodes.track_low003_wall_e_0.geometry} material={nodes.track_low003_wall_e_0.material} />
          </group>
          <group  rotation={[2.21, -0.01, 0.01]} scale={100}>
            <mesh geometry={nodes.track_low004_wall_e_0.geometry} material={nodes.track_low004_wall_e_0.material} />
          </group>
          <group  rotation={[0.01, 0, 0]} scale={100}>
            <mesh geometry={nodes.track_low005_wall_e_0.geometry} material={nodes.track_low005_wall_e_0.material} />
          </group>
          <group  rotation={[2.04, -0.01, 0.01]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low006_wall_e_0.geometry} material={nodes.track_low006_wall_e_0.material} />
          </group>
          <group  rotation={[1.8, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low007_wall_e_0.geometry} material={nodes.track_low007_wall_e_0.material} />
          </group>
          <group  rotation={[1.31, -0.01, -0.02]} scale={100}>
            <mesh geometry={nodes.track_low008_wall_e_0.geometry} material={nodes.track_low008_wall_e_0.material} />
          </group>
          <group  rotation={[0.68, 0, -0.01]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low009_wall_e_0.geometry} material={nodes.track_low009_wall_e_0.material} />
          </group>
          <group  rotation={[0.49, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low010_wall_e_0.geometry} material={nodes.track_low010_wall_e_0.material} />
          </group>
          <group  rotation={[0.39, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low011_wall_e_0.geometry} material={nodes.track_low011_wall_e_0.material} />
          </group>
          <group  rotation={[0.3, 0, 0]} scale={100}>
            <mesh geometry={nodes.track_low012_wall_e_0.geometry} material={nodes.track_low012_wall_e_0.material} />
          </group>
          <group  rotation={[2.16, -0.01, 0.01]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low013_wall_e_0.geometry} material={nodes.track_low013_wall_e_0.material} />
          </group>
          <group  rotation={[0.19, 0, 0]} scale={100}>
            <mesh geometry={nodes.track_low014_wall_e_0.geometry} material={nodes.track_low014_wall_e_0.material} />
          </group>
          <group  rotation={[-0.31, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low015_wall_e_0.geometry} material={nodes.track_low015_wall_e_0.material} />
          </group>
          <group  rotation={[-0.86, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low016_wall_e_0.geometry} material={nodes.track_low016_wall_e_0.material} />
          </group>
          <group  rotation={[-1.34, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low017_wall_e_0.geometry} material={nodes.track_low017_wall_e_0.material} />
          </group>
          <group  rotation={[-1.59, -0.01, 0]} scale={100}>
            <mesh geometry={nodes.track_low018_wall_e_0.geometry} material={nodes.track_low018_wall_e_0.material} />
          </group>
          <group rotation={[-1.62, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low019_wall_e_0.geometry} material={nodes.track_low019_wall_e_0.material} />
          </group>
          <group  rotation={[-1.61, -0.01, 0]} scale={100}>
            <mesh geometry={nodes.track_low020_wall_e_0.geometry} material={nodes.track_low020_wall_e_0.material} />
          </group>
          <group  rotation={[1.35, -0.01, -0.02]} scale={100}>
            <mesh geometry={nodes.track_low021_wall_e_0.geometry} material={nodes.track_low021_wall_e_0.material} />
          </group>
          <group  rotation={[-1.57, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low022_wall_e_0.geometry} material={nodes.track_low022_wall_e_0.material} />
          </group>
          <group position={[0.28, 4.29, 30.85]} rotation={[-1.53, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low023_wall_e_0.geometry} material={nodes.track_low023_wall_e_0.material} />
          </group>
          <group  rotation={[-1.56, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low024_wall_e_0.geometry} material={nodes.track_low024_wall_e_0.material} />
          </group>
          <group  rotation={[-1.83, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low025_wall_e_0.geometry} material={nodes.track_low025_wall_e_0.material} />
          </group>
          <group  rotation={[-2.39, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low026_wall_e_0.geometry} material={nodes.track_low026_wall_e_0.material} />
          </group>
          <group  rotation={[-3.11, -0.01, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low027_wall_e_0.geometry} material={nodes.track_low027_wall_e_0.material} />
          </group>
          <group
            name="track_low028"
            position={[0.23, 63.8, 105.14]}
            rotation={[2.74, -0.01, 0]}
            scale={[100, 100, 100]}>
            <mesh geometry={nodes.track_low028_wall_e_0.geometry} material={nodes.track_low028_wall_e_0.material} />
          </group>
          <group  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.body_low_wall_e_0.geometry} material={nodes.body_low_wall_e_0.material} />
          </group>
          <group  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.back_low_wall_e_0.geometry} material={nodes.back_low_wall_e_0.material} />
          </group>
          <group  rotation={[-Math.PI / 2, 0, 0]} scale={205.08}>
            <mesh geometry={nodes.base_low_wall_e_0.geometry} material={nodes.base_low_wall_e_0.material} />
          </group>
          <group  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.trackDetails001_low_wall_e_0.geometry}
              material={nodes.trackDetails001_low_wall_e_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
